apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "imageswap-webhook.fullname" . }}-mwc-template
  labels:
    {{- include "imageswap-webhook.labels" . | nindent 4 }}
data:
  imageswap-mwc: |
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      name: {{ include "imageswap-webhook.fullname" . }}
      labels:
        {{- include "imageswap-webhook.labels" . | nindent 8 }}
    webhooks:
      - name: imageswap.webhook.k8s.twr.io
        clientConfig:
          service:
            name: {{ include "imageswap-webhook.fullname" . }}
            namespace: {{ .Release.Namespace }}
            path: "/"
          caBundle: $CA_BUNDLE
        rules:
          - operations:
              - CREATE
              - UPDATE
            apiGroups:
              - "*"
            apiVersions:
              - "*"
            resources:
              - "pods"
        sideEffects: None
        admissionReviewVersions: ["v1"]
        failurePolicy: Fail
        reinvocationPolicy: IfNeeded
