kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "imageswap-webhook.fullname" . }}
  labels:
    {{- include "imageswap-webhook.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - update
