apiVersion: v1
kind: Service
metadata:
  name: {{ include "imageswap-webhook.fullname" . }}
  labels:
    {{- include "imageswap-webhook.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  selector:
    {{- include "imageswap-webhook.labels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
